### ISSUE TITLE
Cluster and locking support

### ISSUE THREAD

**Issue by gsmith2409** [glucaci/mongodb-quartz-net#12]
Wondering if this driver has cluster/lock support?

**Comment by dmumladze** [comment]
I don't think cluster support is there at the moment, which is a main showstopper for me at this point, but I'm not 100% sure as I haven't reviewed the code for some time. Main page says the following, so I think the support isn't there:

> Implemented a simple distributed lock on top of Mongo to help with future cluster support based on ideas shared here.

There're some challenges regarding that mainly due to MongoDB's inability to do transactions, but with MongoDB 4.0 release, this problem should be easy to solve.. Also, it's not worth the effort to get the clustering working for anything lower the MongoDB 4.0.

**Comment by chrisdrobison** [comment]
I use it in a cluster and it seems to work for me. Have you tried it in
your scenario ?

**Comment by dmumladze** [comment]
@chrisdrobison Does MonogDB API support Quartz job triggering in load balanced scenario from multiple servers?

**Comment by chrisdrobison** [comment]
I don't think I quite understand your question. This library can work with multiple servers. It's more of a first come first serve basis because of the lock. Give it a shot and see if it works for you. I didn't implement the cluster support that the original library had because I didn't quite see the value since it worked with just a simple lock.

**Comment by dmumladze** [comment]
@chrisdrobison Will give it a try and ping back. Thanks.

**Comment by chrisdrobison** [comment]
Closing. Reopen if necessary.
